### ISSUE TITLE
[BUG] OpenGL Backend not checking for error or warning status

### ISSUE THREAD

**Issue by mathew-odwyer** [mtosoftware/FinalEngine#59]
# Expected Behavior

When calling OpenGL functions, I should be checking whether the functions are throwing any errors of warnings. I should also make sure that the errors are logged, which means that the Logging framework will need to be implemented first. I should be descriptive about which API is throwing the error, just to future-proof:

```csharp
SomeOpenGLCallHere();

var log = GetErrorInformation(invoker.GetError());

if (string.IsNullOrEmpty(log))
{
    return;
}

logger.Log($"OPENGL::{log}");
```

# Current Behavior

I'm not checking if they're throwing any errors or warnings.

**Comment by KinsonDigital** [comment]
Yes, I would definitely check for errors.  But be warned, it is a performance hit when checking for errors.  I watched some videos and read some stuff that said what people usually do is only check for errors in debug mode.  Release builds would not do this due to performance hits.  

The best way is to build in a bool flag that can be used to turn logging on and off.  In your debug builds, default to LogOpenGLErrors to true and for release builds, default it to false.

**Comment by mathew-odwyer** [comment]
That makes sense, although, I vaguely recall that OpenGL has a slightly newer way of checking for errors with a callback - it's something I'll have to look further into but if it works out, we won't have to check for errors after each call :)

**Comment by KinsonDigital** [comment]
Oo...very nice

**Comment by mathew-odwyer** [comment]
[here](https://www.khronos.org/opengl/wiki/Example/OpenGL_Error_Testing_with_Message_Callbacks) it is 😃

**Comment by KinsonDigital** [comment]
Ah ok.  Yep, I think I am already utilizing that.  😊
